image:
  name: peterzel/isabelle:latest
before_script:
  - mkdir -p ~/isabelle-deps
  - curl -o ~/isabelle-deps/fuzzy_rule.zip https://codeload.github.com/peterzeller/isabelle_fuzzy_rule/zip/master
  - unzip ~/isabelle-deps/fuzzy_rule.zip -d ~/isabelle-deps/
  - echo ~/isabelle-deps/isabelle_fuzzy_rule-master >> ~/.isabelle/ROOTS
  - echo ~/isabelle-deps/isabelle_fuzzy_rule-master >> ~/.isabelle/Isabelle2020/ROOTS
compile:
  stage: build
  script:
    - /home/isabelle/Isabelle/bin/isabelle build -D . -j 20 -v -o quick_and_dirty
  artifacts:
    paths:
      - output/*.pdf
      - output/*.log
      - output/document/*.pdf
      - output/document/*.log
      - output/document/*.tex
      - output/document/*.sty
    when: always
    expire_in: 2 weeks
